<?php
$this->headTitle('application_title_error_404');
?>
<br/><br/>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="hero-unit center">
                <h1><?= $this->translate('application_title_error_404'); ?></h1>
                <br/>
                <p>The page you requested could not be found, either contact your webmaster or try again.
                    Use your browsers <b>Back</b> button to navigate to the page you have prevously come from</p>
                <p><b>Or you could just press this neat little button:</b></p>
                <p class="pull-center">
                    <a href="/" class="btn btn-success">
                        <?php echo $this->translate('application_action_homepage'); ?>
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
