<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8">
                <h1 class="display-4">Hello Zend Framework 3!</h1>
                <p>This skeleton is a simple starting point for you to begin building your application on ZF3.</p>
                <p><a class="btn btn-success btn-lg" href="https://zendframework.github.io/zend-mvc/" target="_blank" role="button">Learn
                        more &raquo;</a></p>
            </div>
            <div class="col-md-6 col-lg-4">
                <img src="/img/zf3.png" width="350">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf('Zend Framework 3 is under active development. If you are interested in following the development of ZF3, there is a special ZF3 portal on the official Zend Framework website which provides links to the ZF3 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!', '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/ZF3/blog">', '</a>', '<a href="https://github.com/zendframework/ZF3/issues">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="http://framework.zend.com/"
                          target="_blank"><?php echo $this->translate('ZF3 Development Portal') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf('The community is working on developing a community site to serve as a repository and gallery for ZF3 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF3.', '<a href="https://github.com/zendframework/">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/"
                          target="_blank"><?php echo $this->translate('Explore ZF3 Modules') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
                </div>
                <div class="panel-body">
                    <p><?php echo sprintf('If you need any help or support while developing with ZF3, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.', '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                    <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk"
                          target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; Company 2016</p>
    </footer>
</div>
